[package]
name = "gl_playground"
version = "0.1.0"
authors = ["Christopher Michael Sutton <christopher.sutton12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.26.0"
gl = "0.14.0"
